[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [
    { access = "read", path = "./deployments" },
    { access = "read", path = "./out" },
    { access = "read", path = "./contexts.json" },
]

[fmt]
ignore = ['generated/**/*.sol', "lib/**/*.sol"]

[invariant]
call_override = false  # Override calls
runs = 200             # The number of times to run the invariant tests
depth = 100            # The number of calls to make in the invariant tests
fail_on_revert = false
